openapi: 3.0.0
info:
  title: Lambda
  version: 1.0.0
paths:
  /search:
    get:
      summary: Search
      description: Search AWS blogs
      operationId: search
      parameters:
        - name: search_blog
          in: path
          description: Search keyword
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Search successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  body:
                    type: string
